// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIeBFUUMUYZxP1y3kNLLpnF3VD2wmcl6k',
    appId: '1:13748084728:web:5a2fbb9c62f94b12c2800d',
    messagingSenderId: '13748084728',
    projectId: 'viewgram-7802e',
    authDomain: 'viewgram-7802e.firebaseapp.com',
    storageBucket: 'viewgram-7802e.firebasestorage.app',
    measurementId: 'G-FXWPCERX9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFGl5dLC_8fBydZGqp9k1XSB_2jPdgpUA',
    appId: '1:13748084728:android:b8d46d554d6b63c9c2800d',
    messagingSenderId: '13748084728',
    projectId: 'viewgram-7802e',
    storageBucket: 'viewgram-7802e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGJtI2P05TJqArWgS5hAoe_hJKAGUpIUU',
    appId: '1:13748084728:ios:4864ce8d34cfd126c2800d',
    messagingSenderId: '13748084728',
    projectId: 'viewgram-7802e',
    storageBucket: 'viewgram-7802e.firebasestorage.app',
    iosBundleId: 'com.example.uniqueSocialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGJtI2P05TJqArWgS5hAoe_hJKAGUpIUU',
    appId: '1:13748084728:ios:4864ce8d34cfd126c2800d',
    messagingSenderId: '13748084728',
    projectId: 'viewgram-7802e',
    storageBucket: 'viewgram-7802e.firebasestorage.app',
    iosBundleId: 'com.example.uniqueSocialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIeBFUUMUYZxP1y3kNLLpnF3VD2wmcl6k',
    appId: '1:13748084728:web:919c1404392dc649c2800d',
    messagingSenderId: '13748084728',
    projectId: 'viewgram-7802e',
    authDomain: 'viewgram-7802e.firebaseapp.com',
    storageBucket: 'viewgram-7802e.firebasestorage.app',
    measurementId: 'G-BGTY052LJB',
  );
}
